#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFEEF9FC2DD21D271 (security@readthedocs.org)
#
Name     : pypi-sphinx_rtd_theme
Version  : 1.0.0
Release  : 50
URL      : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz.asc
Summary  : Read the Docs theme for Sphinx
Group    : Development/Tools
License  : MIT OFL-1.1
Requires: pypi-sphinx_rtd_theme-license = %{version}-%{release}
Requires: pypi-sphinx_rtd_theme-python = %{version}-%{release}
Requires: pypi-sphinx_rtd_theme-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(docutils)
BuildRequires : pypi(sphinx)

%description
Read the Docs Sphinx Theme
        **************************

%package license
Summary: license components for the pypi-sphinx_rtd_theme package.
Group: Default

%description license
license components for the pypi-sphinx_rtd_theme package.


%package python
Summary: python components for the pypi-sphinx_rtd_theme package.
Group: Default
Requires: pypi-sphinx_rtd_theme-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_rtd_theme package.


%package python3
Summary: python3 components for the pypi-sphinx_rtd_theme package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_rtd_theme)
Requires: pypi(docutils)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_rtd_theme package.


%prep
%setup -q -n sphinx_rtd_theme-1.0.0
cd %{_builddir}/sphinx_rtd_theme-1.0.0
pushd ..
cp -a sphinx_rtd_theme-1.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656369880
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . docutils
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . docutils
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_rtd_theme
cp %{_builddir}/sphinx_rtd_theme-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_rtd_theme/a1476f264c3622ce6548208ab116bf128809ddf7
cp %{_builddir}/sphinx_rtd_theme-1.0.0/OFL-License.txt %{buildroot}/usr/share/package-licenses/pypi-sphinx_rtd_theme/515c9e4e8cd9008dd8c0685638dfe9186aaad429
python3 -tt setup.py build  install --root=%{buildroot}
pypi-dep-fix.py %{buildroot} docutils
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_rtd_theme/515c9e4e8cd9008dd8c0685638dfe9186aaad429
/usr/share/package-licenses/pypi-sphinx_rtd_theme/a1476f264c3622ce6548208ab116bf128809ddf7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
