#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinx_rtd_theme
Version  : 0.2.5b2
Release  : 1
URL      : https://github.com/rtfd/sphinx_rtd_theme/archive/0.2.5b2.tar.gz
Source0  : https://github.com/rtfd/sphinx_rtd_theme/archive/0.2.5b2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: sphinx_rtd_theme-python3
Requires: sphinx_rtd_theme-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
.. _readthedocs.org: http://www.readthedocs.org
.. _bower: http://www.bower.io
.. _sphinx: http://www.sphinx-doc.org
.. _compass: http://www.compass-style.org
.. _sass: http://www.sass-lang.com
.. _wyrm: http://www.github.com/snide/wyrm/
.. _grunt: http://www.gruntjs.com
.. _node: http://www.nodejs.com
.. _demo: http://docs.readthedocs.org
.. _hidden: http://sphinx-doc.org/markup/toctree.html

%package legacypython
Summary: legacypython components for the sphinx_rtd_theme package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the sphinx_rtd_theme package.


%package python
Summary: python components for the sphinx_rtd_theme package.
Group: Default
Requires: sphinx_rtd_theme-python3

%description python
python components for the sphinx_rtd_theme package.


%package python3
Summary: python3 components for the sphinx_rtd_theme package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sphinx_rtd_theme package.


%prep
%setup -q -n sphinx_rtd_theme-0.2.5b2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518790167
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1518790167
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
