#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFEEF9FC2DD21D271 (security@readthedocs.org)
#
Name     : sphinx_rtd_theme
Version  : 1.0.0
Release  : 38
URL      : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/1c/32/580309c9fd5b1892c6616ce814710c6b14423e98bf1c101bf2c710433cee/sphinx_rtd_theme-1.0.0.tar.gz.asc
Summary  : Read the Docs theme for Sphinx
Group    : Development/Tools
License  : MIT OFL-1.1
Requires: sphinx_rtd_theme-license = %{version}-%{release}
Requires: sphinx_rtd_theme-python = %{version}-%{release}
Requires: sphinx_rtd_theme-python3 = %{version}-%{release}
Requires: Sphinx
Requires: docutils
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : docutils

%description
Read the Docs Sphinx Theme
        **************************

%package license
Summary: license components for the sphinx_rtd_theme package.
Group: Default

%description license
license components for the sphinx_rtd_theme package.


%package python
Summary: python components for the sphinx_rtd_theme package.
Group: Default
Requires: sphinx_rtd_theme-python3 = %{version}-%{release}

%description python
python components for the sphinx_rtd_theme package.


%package python3
Summary: python3 components for the sphinx_rtd_theme package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_rtd_theme)
Requires: pypi(docutils)
Requires: pypi(sphinx)

%description python3
python3 components for the sphinx_rtd_theme package.


%prep
%setup -q -n sphinx_rtd_theme-1.0.0
cd %{_builddir}/sphinx_rtd_theme-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631636614
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinx_rtd_theme
cp %{_builddir}/sphinx_rtd_theme-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/sphinx_rtd_theme/a1476f264c3622ce6548208ab116bf128809ddf7
cp %{_builddir}/sphinx_rtd_theme-1.0.0/OFL-License.txt %{buildroot}/usr/share/package-licenses/sphinx_rtd_theme/515c9e4e8cd9008dd8c0685638dfe9186aaad429
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinx_rtd_theme/515c9e4e8cd9008dd8c0685638dfe9186aaad429
/usr/share/package-licenses/sphinx_rtd_theme/a1476f264c3622ce6548208ab116bf128809ddf7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
